# Generated by Django 5.1 on 2024-08-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_inventario_denominacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='ano_ingreso',
            field=models.DateField(),
        ),
    ]
